sudo: false
language: node_js
node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER process.env.DB_USER WITH PASSWORD process.env.DB_PASSWORD';" -U postgres
install:
  - npm install

script:
  - npm run test
  
after_success: 
  - npm run coverage
