sudo: false
language: node_js
node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database test_automart;' -U postgres
  - psql -c "CREATE USER automart WITH PASSWORD 'password';" -U postgres
install:
  - npm install

script:
  - npm run test
  
after_success: 
  - npm run coverage
